### ISSUE TITLE
Exception EOutOfMemory in module Imgextractor.exe at 0001661D

### ISSUE THREAD

**Issue by yougikou** [upleung/Android10-system.img-unpack#1]
对华为EMUI 9的system.img解包。
先用Huawei Update Extractor 将UPDATA.APP中的SYSTEM.img文件提取出来。
然后SYSTEM.img重命名为「system.new.img」剪切到SystemExtractor里的extract_file_here文件夹。
执行img解包.cmd，选择1 - Unpacking "system.new.dat".
出现以下log

Type option:1

Please wait, start conversion in "system.new.img"...

Traceback (most recent call last):
  File "sdat2img.py", line 86, in <module>
  File "sdat2img.py", line 66, in main
  File "sdat2img.py", line 32, in parse_transfer_list_file
FileNotFoundError: [Errno 2] No such file or directory: 'place_for_system.new.dat_system.transfer.list_here\\system.transfer.list'

Please wait, unpacks "system.new.img"...

ImgExtractor version 1.3.6 <Created by And_PDA (Based on sources ext4_unpacker)>

Extractor for images in EXT2\EXT3\EXT4\YAFFS2\CRAMFS filesystem formats
support SPARSE\SIN\MOTO structure formats

Exception EOutOfMemory in module Imgextractor.exe at 0001661D.
Out of memory.

Done. Go to the folder "extract_file_here"
请按任意键继续. . .

曾经参照XDA上的 Imgextractor.exe 教程，单独命令行执行过。
也得到同样错误。

由于我日本机器刷了港版。Felica电子钱包废了不说，NFC也不能用，实在有点不爽。
想从日版P30 Pro(Docomo HW-02L)的EMUI9固件中获取 NFC/Felica相关文件，
碰碰运气，看看简单移植到港版EMUI10固件中是否可用。

**Comment by ghost** [comment]
直接mount该img就行了，可以不用解包

**Comment by afatcat-xie** [comment]
你都没有提取system.transfer.list，当然找不到文件了
